---


- name: Download Composer installer checksum
  get_url:
    url: https://composer.github.io/installer.sig
    dest: /tmp/composer-installer.sig

# !@#!@
- slurp:
    path: /tmp/composer-installer.sig
  register: composer_checksum

- name: Download Composer installer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: "sha384:{{ composer_checksum.content | b64decode}}"

- name: Install Composer
  command: "php composer-setup.php --quite --version={{ composer_version }}"
  args:
    chdir: /tmp
    creates: /tmp/composer.phar

- name: Ensure Composer is available globally
  become: true
  shell: cp /tmp/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  tags:
    - composer

- name: Set permissions on composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"
  tags:
    - composer